### 신규 예매 등록
POST localhost:8081/api/v1/bookings/new
Content-Type: application/json

{
  "userId": "1",
  "screeningId": "1",
  "seatId": "3",
  "totalPrice": "10000"
}

### 예매 내역 조회
GET localhost:8081/api/v1/bookings/booking/1

### 예매 내역 전체 조회
GET localhost:8081/api/v1/bookings/user/1