### 신규 영화 등록
POST localhost:8081/api/v1/movies/new
Content-Type: application/json

{
  "title": "청설",
  "subTitle": "Hear Me: Our Summer",
  "description": "가슴으로 사랑을 느끼는, 청량한 설렘의 순간",
  "releaseDate": "2024.10.27",
  "durationMinutes": "108",
  "posterUrl": "test@test.com",
  "ageRating": "ALL",
  "director": "조선호",
  "screeningType": "TWO_D",
  "standardPrice": "10000",
  "genreTypes": ["DRAMA"],
  "actors": [
    "홍경",
    "노윤서",
    "김민주"
  ]
}

### 전체 영화 조회
GET localhost:8081/api/v1/movies